// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhsqefhadcyjfnzmnrto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFoc3FlZmhhZGN5amZuem1ucnRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1ODIxNzgsImV4cCI6MjA2NzE1ODE3OH0.zh1WavdNNWYnpfVf1Z6bMA38HH2QhhY0CFBkqYWzVZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});